### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by djfdat** [djfdat/phaser-typescript-vscode-boilerplate#5]
- [x] Create standard node .gitignore
- [ ] Document added step of running npm install in readme

**Comment by brandonmanke** [comment]
#8 I created a pull request with a node .gitignore. Also, could you specify what you mean by "Document added step of running npm install in readme"? I'd be happy to work on that as well, thanks!

**Comment by djfdat** [comment]
The document task is just to add to README.md the fact that you now need to run npm install before this will work.

**Comment by Subway19** [comment]
I would like to claim this. This would be my first open source pull request.
