### ISSUE TITLE
Add npm install task to vscode

### ISSUE THREAD

**Issue by djfdat** [djfdat/phaser-typescript-vscode-boilerplate#6]
- [x] Create vscode task for running npm install
- [x] Add/edit step for doing npm install through vscode to readme

**Comment by schenkfab** [comment]
Hi @djfdat I'd like to take that if it's ok?

**Comment by djfdat** [comment]
Go for it! Thanks!

**Comment by schenkfab** [comment]
@djfdat As you do not have a package.json file, what should happen if npm install is being run?

**Comment by djfdat** [comment]
Sorry about that. The only dependency it has is node-static. If you'd like to make that, you're welcome to do so, if not, I may be able to get to it tonight.

**Comment by schenkfab** [comment]
Sure, I'll do it :+1:

**Comment by Subway19** [comment]
I would like to claim this. This would be my first open source pull request.
